import type {ScoutFolder} from '../types';
import {optionalClient, raise, requireClient} from './client';
import {rowToFolder} from './mappers';
import type {FolderRow} from './rows';

export async function list(orgId: string): Promise<ScoutFolder[]> {
  const client = optionalClient();
  if (!client) {
    return [];
  }
  const {data, error} = await client
      .from('folders')
      .select('id,org_id,name,parent_id,created_at,icon,color,kind')
      .eq('org_id', orgId)
      .order('created_at', {ascending: true});
  raise(error, 'folders.list');
  return ((data || []) as unknown as FolderRow[]).map(rowToFolder);
}

// The id is generated by the caller (crypto.randomUUID) rather than by the
// column default, because the UI selects the new folder immediately.
export async function create(orgId: string, folder: ScoutFolder): Promise<void> {
  const client = requireClient();
  const {error} = await client.from('folders').insert({
    id: folder.id,
    org_id: orgId,
    name: folder.name,
    // Written explicitly rather than left to the column default: a folder
    // created without a kind would silently become a profile folder and
    // disappear from the tab that made it.
    kind: folder.kind || 'profile',
    icon: folder.icon ?? null,
    color: folder.color ?? null,
    created_at: folder.created_at || new Date().toISOString(),
  });
  raise(error, 'folders.create');
}

// Was rename(orgId, id, name). It edits three columns now, and a function
// called `rename` that also sets the icon would be lying about what it does.
export async function update(
    orgId: string,
    id: string,
    patch: {name?: string; icon?: string | null; color?: string | null}): Promise<void> {
  const client = requireClient();
  const {error} = await client
      .from('folders')
      .update(patch)
      .eq('org_id', orgId)
      .eq('id', id);
  raise(error, 'folders.update');
}

// Profiles in this folder are moved to "All profiles" by the FK's
// ON DELETE SET NULL -- no second statement needed.
export async function remove(orgId: string, id: string): Promise<void> {
  const client = requireClient();
  const {error} = await client
      .from('folders')
      .delete()
      .eq('org_id', orgId)
      .eq('id', id);
  raise(error, 'folders.remove');
}
